submit job object to smartslice
tetonsim/thorjs pull request #16
Opened 2021-03-25 23:36 UTC by colman-hartinger

The correct header was already being set if a 'fast-job' object was submitted so I just made some minor changes so that the cli tool can also submit a 'fast-job' file. What I thought was the meat of this PR is setting up a class so developers can properly create job objects using thorJS. 

I was going back and forth on the best way to properly setup the job object and decided on building the job class with typedefs for each object being passed in. I wasn't sure if the class should just return the a javascript object from the job or write a file so for the time being I have it writing a file as 'fast-job.smart'. If you think that we should go into more detail for the typedefs I think it could be beneficial to use typescript instead of javascript

2021-03-26 13:09 UTC, bradymadams requested changes
> What I thought was the meat of this PR is setting up a class so developers can properly create job objects using thorJS

Actually, I wanted this just to focus on submitting JSON via the `POST /smartslice` endpoint. I was going to create separate tickets for that, but that's partially my fault for not getting around to that so you could see how I wanted to divvy up the work.

Let's maybe stash job.js for now. It looks like it's pretty far from complete (I know you're just looking for early feedback), and I just want to focus on submitting a JSON through cli.js and api.js for this particular issue. My goal was to get you some familiarity with thorjs with some smaller tickets before having you jump into creating the Job and Result classes.

I think you need to think about a couple things here:

1. All original references to threemfs in the code paths are still there. For example the cli.js help menu for submitting a job doesn't even reflect that you can provide a JSON file. Update variable names or split logic out for the two cases.
2. I'm not sure how I feel about adding a `smart` attribute to a Buffer object. It seems a little hacky to me. I think if you make appropriate changes for 1 above then this shouldn't be necessary. It seems to work, but to be honest, it made me scratch my head a little bit when I first saw it.

For 2 -- I think some confusion might be lifted if you go back to #13 and look at this line:

> Also add a way to cli.js to parse a JSON file into a job object and submit it.

If you setup a new command in cli.js for JSON files and use `JSON.parse` to get an actual object then you won't need to differentiate between the types of data `Buffer` might hold because you'll be using a javascript object instead. Arguably, reading into a Buffer will be faster than parsing and then stringifying the same data, but we're not dealing with a large amount of data here. And I think parsing/stringifying has the advantage that it will remove whitespace from the final data that is unnecessary to send to the API (and bloats the payload by quite a bit).

I should clean up my language as well. Instead of "job object" I should be saying "javascript object" for this issue since I'm just interested in reading a JSON into a standard object and submitting that.

Once we start using the Job class then I'll start using "job object" to represent instances of the Job class.

Sorry for the confusion from my end - this week has been busy and I forgot to create the rest of this tickets. I'll try to get to that on Monday. Hopefully, it's a little more clear what we're looking for here - ping me if it's not.

2021-03-26 13:09 UTC, bradymadams commented on src/job.js
> +  buildSmartFile() {
I think `write` would be a more standard verb here than `build`.

2021-03-26 15:06 UTC, colman-hartinger commented
@bradymadams Ok everything is a lot more clear now, I should have asked more questions during the week as well. I'll make all those changes and get things working properly.

2021-03-26 20:44 UTC, colman-hartinger commented
@bradymadams  sorry for jumping the gun a bit on starting the "job builder" class I guess I got a little ahead of myself. Everything should be working bit more succinctly now

2021-03-29 13:31 UTC, bradymadams requested changes
Neither submission technique works for me. They both throw the below error.

```
brady@mistymoon:~/dev/thorjs$ node src/cli.js smartslice submit ~/sim/smartslice/fast-job.smart json
CTRL+C to cancel job
7:26:43 AM - Job ae7b7de4c14b46088e265686f93da256: running (0)
7:26:45 AM - Job ae7b7de4c14b46088e265686f93da256: running (0)
/home/brady/dev/thorjs/src/cli.js:420
          console.log(`Job finished, writing result to ${outputFile}`);
```

2021-03-29 13:31 UTC, bradymadams commented on src/cli.js
> +    .command('submit <file> [type]')
I can read the code to find out what valid "types" are, but it's not obvious if I'm just using the cli. Make it user friendly by documenting the arguments. Would it make sense to have different commands for each type?

2021-03-29 13:31 UTC, bradymadams commented on src/cli.js
> +    }) ;
I've noticed you'll add an empty line before a closing brace often. Is this part of the JS style we adopted?

2021-03-29 13:31 UTC, bradymadams commented on src/cli.js
> +    path.basename(job, '.3mf') + '.json'
What will happen here if it's not a 3mf?

2021-03-29 15:29 UTC, colman-hartinger commented
> Neither submission technique works for me. They both throw the below error.
> 
> ```
> brady@mistymoon:~/dev/thorjs$ node src/cli.js smartslice submit ~/sim/smartslice/fast-job.smart json
> CTRL+C to cancel job
> 7:26:43 AM - Job ae7b7de4c14b46088e265686f93da256: running (0)
> 7:26:45 AM - Job ae7b7de4c14b46088e265686f93da256: running (0)
> /home/brady/dev/thorjs/src/cli.js:420
>           console.log(`Job finished, writing result to ${outputFile}`);
> ```

That's strange they were both working for me. Are you just using the 'fast-job.smart' file?

2021-03-29 15:32 UTC, colman-hartinger commented on src/cli.js
> +    .command('submit <file> [type]')
I was debating separating this out into two commands but decided as keeping it as one to keep the code simpler. I'll change this so it there are two commands for the separate job types since that should be easier to use

2021-03-29 15:32 UTC, colman-hartinger commented on src/cli.js
> +    }) ;
no this is just a error on my part

2021-03-29 15:32 UTC, bradymadams commented
> That's strange they were both working for me. Are you just using the 'fast-job.smart' file?

I tried both techniques - 3MF and JSON. The `outputFile` variable is not defined in `submitAndPoll`. Are you sure it's working for you? If so, you must have some local changes that you haven't pushed.

2021-03-29 15:33 UTC, colman-hartinger commented on src/cli.js
> +    path.basename(job, '.3mf') + '.json'
It should still work since it's just the name of the output file but I should change that as to not create confusion

2021-03-29 15:37 UTC, colman-hartinger commented
> . Are you sure it's working for you? If so, you must have some local changes that you haven't pushed.

Ok I was just aborting the job before it hit the error I'll get that fixed

2021-03-29 19:07 UTC, colman-hartinger commented on src/cli.js
> +    path.basename(job, '.3mf') + '.json'
so now the output file will turn 'fast-job.smart' -> fast-jobsmart.json' or 'test.3mf' -> 'test3mf.json'

2021-03-29 19:37 UTC, bradymadams requested changes

2021-03-29 19:37 UTC, bradymadams commented on src/api.js
> +
Is this empty line needed?

2021-03-29 19:37 UTC, bradymadams commented on src/cli.js
> +    });
Extra indentation?

2021-03-29 19:37 UTC, bradymadams commented on src/cli.js
> +    .command('submit <file>')
Since you've split out the commands I think it would be more helpful to imply the file type like it was before, rather than just `<file>`. Or document the options.

2021-03-29 19:37 UTC, bradymadams commented on src/cli.js
> +  .command('submitJSON <file>' )
I would prefer the standard "submit" takes a JSON since I want to move our API to using JSON as default rather than 3MF. So I would suggest we rename the commands to `submit` for JSON and `submit3MF` for 3MF.

2021-03-29 19:37 UTC, bradymadams commented on src/cli.js
> +        if (type === 'json') {
There are only two file types, how about using a boolean rather than a string? `is3mf`

2021-03-30 13:19 UTC, bradymadams requested changes

2021-03-30 13:19 UTC, bradymadams commented on src/cli.js
> +  .action( job => {
Extra space before `job`

2021-03-30 15:33 UTC, bradymadams commented
When I run `submit` with a 3MF the JSON parse fails, which is expected, but it would be good to catch that exception and issue a more helpful error message that says the JSON parse failed and if the file is a 3MF to use the `submit3mf` command instead.

2021-03-30 17:14 UTC, colman-hartinger commented on src/cli.js
> +  .action( job => {
sorry about these silly formatting errors, My js ide wasn't set properly after I reset my computer a while back

2021-03-30 17:14 UTC, bradymadams requested changes

2021-03-30 17:14 UTC, bradymadams commented on src/cli.js
> +            )
Semi-colons.

2021-03-30 17:14 UTC, bradymadams commented on src/cli.js
> +              throw new Error('3MF files not supported. Try submit3mf command')
Are the CLI commands case sensitive? If so, `submit3mf` is not consistent with `submit3MF`. 

I think "not supported" is misleading. How about about "JSON failed to parse. If this is a 3MF file use the submit3MF command"? I would use the same error message whether the file name includes 3MF or not, so the user knows the reason the error threw was the JSON failed to parse. Because if they did submit a JSON but it was malformed the below message about File type not supported wouldn't be very helpful.

2021-03-30 17:14 UTC, bradymadams commented on src/api.js
> +   */
Are you positive this is the correct way to define an argument that would be one of two types? Do you have a link to somewhere that explains this?

2021-03-30 17:19 UTC, colman-hartinger commented on src/api.js
> +   */
the brackets indicate that the property is optional but I was just reading that you can use the 'or' operator in the jsdoc declaration so I'll change it to that

2021-03-30 17:20 UTC, bradymadams commented on src/api.js
> +   */
Wouldn't that mean the object has a "job" attribute that could be an object or a Buffer?

2021-03-30 17:33 UTC, bradymadams requested changes
Please make sure you are reviewing your git diffs before you commit and request reviews, if you are not already.

2021-03-30 17:33 UTC, bradymadams commented on src/cli.js
> +            throw new Error(' "JSON failed to parse. If this is a 3MF file use the submit3MF command');
Erroneous characters.

2021-03-30 19:03 UTC, bradymadams approved these changes

2021-03-30 19:03 UTC, merged