job initialiation file and export
tetonsim/thorjs pull request #26
Opened 2021-04-07 19:55 UTC by colman-hartinger

Pull request for job initialization classes

2021-04-08 14:20 UTC, bradymadams requested changes
I made a couple reference to this in the line by line comments, but I think we should consider organizing into submodules, just like we do in pywim. It will be much easier to maintain going forward. And it will be more consistent with the REST API documentation, allowing developers to more easily identify how to build up a Job object.

Two things to think about:

1. What would it take to read a JSON file into a Job instance?
2. We'll want to test your structure through actual calls to the SmartSlice API before we merge anything.

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +const defaultPrintConfig: PrintConfig = {
I like the idea of providing a way to populate a default config. Can you show me how you would create a default PrintConfig and then make changes to it? It seems like the following would not compile:

```
let config = defaultPrintConfig;
config.walls = 4;
```

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +  skin_orientations: [1],
All of the above defaults need some adjustment. Probably should just copy what we do in pywim: https://github.com/tetonsim/pywim/blob/1c752bdd75d4dcb2c377da855b7438185217a95f/pywim/am.py#L50

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +export class Model {
In pywim we use submodules a lot to organize classes. `Model` is a bit ambiguous, so this is a good example of where organization helps. How can we organize classes in the same way that they are documented in the REST API documentation - e.g. `chop.model.Model`

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +  meshes: Mesh[] | Array<null>;
Is there a difference between `Array<Mesh>` and `Mesh[]`?

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +    this.density = density ? density : 1
Default to 0.

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +    this.failure_yield = failure_yield ? failure_yield : { type: 'von_mises', Sy: 1 }
For elastic, fracture, and failure_yield, if they're not specified I'd rather they be null. Otherwise having defaults for these could potentially cause big problems with results if the developer doesn't explicitly override each one.

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +export interface Extruders {
This should be singular, but I recognize how this would conflict with the below definition. See my other comment about organizing into submodules.

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +export class Extruder {
Why don't these classes implement the related interface?

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +    this.usable_material = usable_material ? usable_material : ['defatult']
Spelling, but I think it should probably be an empty array by default.

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +    this.number = number ? number : 1
Counting starts at 0.

2021-04-08 14:20 UTC, bradymadams commented on src/thor.ts
> +import * as JobDefinitions from './job'
This is an atypical name IMO.

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +  }
I made a comment on this in a previous PR. There should just be a `toJSON` function.

Adding the serialized version of the job to the class that needs to be updated through a function call is asking for trouble. Everytime the job object is mutated then you immediately have inconsistent state. Much easier if you just don't store the serialized string (especially since the class doesn't need it for anything). Let the calling code request and retrieve it through a function call.

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +    };
This confuses me. This means all of these objects live in two different places. Under SmartSliceJob and under SmartSliceJob.job. Please think about this from the perspective of a new developer using this code. I don't see why the `job` attribute is necessary at all.

2021-04-08 14:20 UTC, bradymadams commented on src/job.ts
> +export class SmartSliceJob implements Job {
Can we just name this class `Job`?

2021-04-08 16:30 UTC, colman-hartinger commented on src/job.ts
> +  meshes: Array<Mesh> | Array<null>;
an empty array: []

2021-04-08 16:39 UTC, colman-hartinger commented on src/job.ts
> +const defaultPrintConfig: PrintConfig = {
that compiled when I tried those exact lines of code. How were you running it?

2021-04-08 16:40 UTC, colman-hartinger commented on src/job.ts
> +  skin_orientations: [1],
got it, I wasn't completely sure what to set the defaults to

2021-04-08 16:40 UTC, colman-hartinger commented on src/thor.ts
> +import * as JobDefinitions from './job'
do you think just Job would be better?

2021-04-08 16:41 UTC, colman-hartinger commented on src/job.ts
> +export class SmartSliceJob implements Job {
Ya I'm not sure what I was thinking when I named this

2021-04-08 16:52 UTC, bradymadams commented on src/job.ts
> +  meshes: Array<Mesh> | Array<null>;
Can `Array<Mesh>` not be an empty array?

2021-04-08 16:53 UTC, bradymadams commented on src/job.ts
> +const defaultPrintConfig: PrintConfig = {
> that compiled when I tried those exact lines of code. How were you running it?

I didn't run it. My intuition tells me that if I set something to reference a const object and try to change that object that it shouldn't change.

So if that works, what is happening? Is a copy of defaultPrintConfig being made? Or is the defaultPrintConfig object being changed? If the latter, that will definitely cause bugs.

2021-04-08 16:55 UTC, bradymadams commented on src/thor.ts
> +import * as JobDefinitions from './job'
I'd like to see how the module reorganization goes and maybe mimic pywim. So maybe "SmartSlice.Job"?

2021-04-08 16:55 UTC, colman-hartinger commented on src/job.ts
> +  meshes: Array<Mesh> | Array<null>;
ya it can I'll change that

2021-04-08 17:10 UTC, colman-hartinger commented on src/job.ts
> +const defaultPrintConfig: PrintConfig = {
It looks like the original defaultPrintConfig object is being mutated in that scenario. I'll change `defaultPrintConfig` to a class object so that a new object has to be created every time and the default values won;' mutate

2021-04-08 19:15 UTC, colman-hartinger commented on src/job.ts
> +  extruders: {
the printer isn't defined as a list in the api documentation but the extruders should be a list. https://test.smartslice.xyz/doc/index.html#chop.machine.Printer

2021-04-08 19:18 UTC, bradymadams commented on src/job.ts
> +  extruders: {
I was just referring to the extruders attribute. Printer is just a singular object, not a list.

2021-04-08 20:49 UTC, colman-hartinger commented on src/job.ts
> +export class Extruder {
using the same name in typescript is a form of polymophism
```
interface Extruder {
   foo:string
}

class Extruder {
  foo:string
  
  bar () {
    //some method
  } 
}
```
is the same as

```
interface Extruder {
   foo:string
}

class Extruder implements Extruder {
  foo:string
  
  bar () {
    //some method
  } 
}
```

2021-04-08 21:11 UTC, bradymadams commented on src/job.ts
> +export class Extruder {
Got it, I did not know that. Interesting language design choice. Thanks for explaining :+1:

2021-04-09 22:04 UTC, bradymadams requested changes
This review isn't super in-depth. Overall, I think the new organization looks good.

1. One thing I noticed was inconsistency between using `Array<T>` and `T[]`. Is there a reason to mix them or should we pick one convention and stick with it?
2. The indentation on some of the interfaces and classes isn't right. Some have extra indentation. Some only indent 1 space for each level (mesh.ts for example).
3. There's a couple places where I think it would be better to use enums rather than string types. Like on Job.type and Elastic.type. Pretty much any `type` attribute should probably be an enum. I know the REST API documentation doesn't specify enums, but that's because it's documenting raw JSON, so enums aren't valid in that context.

2021-04-09 22:04 UTC, bradymadams commented on src/smartslice/job/job.ts
> +  toJSON(): string {
I think the standard design here is to return the object that needs to be stringified. `JSON.stringify` will look for `toJSON` to get an object, so you can then call `JSON.stringify(new Job())`.

And taking that one step further - I think if the object you return from toJSON isn't any different than the Job object you may not need `toJSON` at all. I think `JSON.stringify` will properly stringify class instances.

See the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description) for more info.

2021-04-12 20:38 UTC, colman-hartinger commented on src/chop/model/load.ts
> +    face: Array<number>;
no I don't think `bigint` would be better. I was looking into it a bit and it seems like there are performance problems with `bigint` 

Also 
```
// Option 1
interface foo {
  num: bigint
}

const bar: foo = 1 // would not compile because type(1) isn't bigint
const bar: foo = 1n // would compile

// Option 2
type Int = number & { __int__: void }
let bar: Int = 1 //would not compile because type(1) isn'tInt
let bar: Int = 1 as Int // would compile since Int type is cast onto number
```

which I think could cause some confusion as the ints would have to be converted to numbers before any arithmetic is done using them

2021-04-12 20:42 UTC, bradymadams commented on src/chop/model/load.ts
> +    face: Array<number>;
Okay fair enough. I didn't realize that. Thanks for the explanation.

2021-04-13 15:20 UTC, colman-hartinger commented
@bradymadams this should be ready for review now


>     1. One thing I noticed was inconsistency between using `Array<T>` and `T[]`. Is there a reason to mix them or should we pick one convention and stick with it?

`Array<T>` and `T[]` evaluate to the same thing. I think the convention is to use the longhand definitions when defining types and interfaces and then using shorthand when defining subsequent classes/functions/objects. Which is the styling I was trying to implement. I have no problem if you think we should just use one or the other though.

2021-04-13 15:25 UTC, bradymadams commented
> `Array<T>` and `T[]` evaluate to the same thing. I think the convention is to use the longhand definitions when defining types and interfaces and then using shorthand when defining subsequent classes/functions/objects. Which is the styling I was trying to implement. I have no problem if you think we should just use one or the other though.

If that's standard convention then I'm fine with that :+1:

2021-04-14 15:09 UTC, bradymadams requested changes
This looks good. Thanks for writing up a test that explicitly builds the Job. Let's remove the src/scripts folder before we merge. I'm all for having tests in the repo, and I understand the value in having those in there for iterating on this PR, but if we put tests into the release branches we'll want to use a proper test framework.

Looks like an empty file was added (.env) - is that necessary?

2021-04-14 15:09 UTC, bradymadams commented on src/fea/model/material.ts
> +    name?: string,
Let's make `name` the first argument. It's the most common argument to be included.

2021-04-14 15:09 UTC, bradymadams commented on src/smartslice/job/job.ts
> +};
Can you explain the reasoning for lines 59-107 and how they would be used in a way that is better than importing those submodules explicitly?

2021-04-14 15:45 UTC, colman-hartinger commented on src/smartslice/job/job.ts
> +};
I thought it could be useful to have a single entrypoint for job building that follows the api namespace documentation. That way you can just use

```
const bc = new chop.model.BoundaryCondition();
const load = new chop.model.Load();
```
But I also don't see any problem with just using relative imports from the submodules so if you think we should get rid of this I'm all for it

2021-04-14 15:51 UTC, bradymadams commented on src/smartslice/job/job.ts
> +};
I guess it seems kind of roundabout to me. In thor.ts you import them from smartslice/job/job, but couldn't they just as easily be imported from their actual locations. I think it might be kind of confusing to have two ways to import the same modules.

2021-04-14 17:25 UTC, colman-hartinger commented on src/chop/model/boundaryCondition.ts
> +  fixed = 'fixed'
semi-colons aren't used on typescript enums. https://www.typescriptlang.org/docs/handbook/enums.html

there should be a trailing comma though

2021-04-14 17:33 UTC, colman-hartinger commented on src/chop/mesh/mesh.ts
>      triangles?: VectorArray,
should the types still be identical or should `IndexArray` be more general?

I could do something like this

```
type VectorArray<T> = Array<[T, T, T]>;

type VertexArray = VectorArray<number>
type IndexArray < T > = VectorArray< T >
```

2021-04-14 17:39 UTC, bradymadams commented on src/chop/mesh/mesh.ts
>      triangles?: VectorArray,
I think you could leave VectorArray as is, and basically setup IndexArray exactly the same. It will basically just be an alias for VectorArray, but I think it'll be more clear that it's an array of integer indices.

Although now that you mention it. For the vertices maybe `VertexArray` would be a better name since it's an array of vertex coordinates and not vectors. So:

```
vertices?: VertexArray,
triangles?: IndexArray
```

Does that fully answer your question?

2021-04-14 17:40 UTC, colman-hartinger commented on src/chop/mesh/mesh.ts
>      triangles?: VectorArray,
ya it does

2021-04-15 17:29 UTC, bradymadams approved these changes
Looks good @colman-hartinger

2021-04-15 17:29 UTC, merged