R21.0 gzip job data
tetonsim/thorjs pull request #29
Opened 2021-04-13 23:37 UTC by colman-hartinger

adds functionality to send gzipped job data, unzip compressed results and set encodings for different endpoints. 

I do think that the `_request` function should be turned into a class so that it can get around the maze of if statements in its current state and also be more malleable for the different endpoint calls being made.

2021-04-14 15:24 UTC, bradymadams requested changes
Mostly looks good. Just needs some more explicit definitions and checking on the two different encoding headers.

2021-04-14 15:24 UTC, bradymadams commented on src/api.ts
> +        if (xhttp.getResponseHeader('content-encoding') == 'gzip') {
Use `Content-Encoding` to match the MDN documentation and line 188.

2021-04-14 15:24 UTC, bradymadams commented on src/api.ts
> +        zlib.gzip(JSON.stringify(data), (err, gz) => {
You should only gzip if the `encoding` variable indicates it (see my comments on the `Encoding` type). Checking `encoding` on line 183 would be more robust and flexible than checking for an attribute that indicates it's a job.

2021-04-14 15:24 UTC, bradymadams commented on src/api.ts
>        xhttp.send(data);
We should also gzip 3MF data.

2021-04-14 15:24 UTC, bradymadams commented on src/types.d.ts
> +  type: string
I don't think the header name needs to be set in `accept`. The header names can be hardcoded since they're defined by the HTTP standard.

I would change this to specify the _values_ of the two headers `Content-Encoding` and `Accept-Encoding`. Those two are separate headers that mean different things. Let me know if you need some clarification on that.

2021-04-14 15:38 UTC, colman-hartinger commented on src/api.ts
> +        if (xhttp.getResponseHeader('content-encoding') == 'gzip') {
I thought the lower case string was how the header was stored https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders

2021-04-14 15:46 UTC, bradymadams commented on src/api.ts
> +        if (xhttp.getResponseHeader('content-encoding') == 'gzip') {
I think it might be converted and stored lowercase. I've always specified headers how the MDN documentation presents them though. I guess either way is fine with me, but for the sake of consistency let's choose one and stick with it in the code.

2021-04-14 15:47 UTC, bradymadams commented on src/api.ts
> +        if (xhttp.getResponseHeader('content-encoding') == 'gzip') {
Sorry @colman-hartinger I was reading through too fast and didn't realize this wasn't setting a header, but getting a header value. Does using `Content-Encoding` not work on `getResponseHeader`?

2021-04-14 15:50 UTC, colman-hartinger commented on src/api.ts
> +        if (xhttp.getResponseHeader('content-encoding') == 'gzip') {
I only tried using the lower-case string so I'll, test out if `Content-Encoding` also works

2021-04-14 16:12 UTC, bradymadams commented on src/api.ts
>        xhttp.send(data);
I should expand on this. I know 3MFs are already zip files, but unfortunately I've seen a couple of instances where the files get zipped in Python with the default of [ZIP_STORED](https://docs.python.org/3/library/zipfile.html#zipfile.ZIP_STORED), which doesn't compress the data.

2021-04-16 12:36 UTC, bradymadams requested changes
I like how you set up the types. Just a few small change requests.

Is there a difference in meaning between a file named `types.ts` and `types.d.ts`?

2021-04-16 12:36 UTC, bradymadams commented on src/types.ts
> +  type: T;
Let's call it `name` to stay consistent with the http standards.
https://developer.mozilla.org/en-US/docs/Web/API/Headers/append

2021-04-16 12:36 UTC, bradymadams commented on src/api.ts
> +      });
We should check that the encoding header was set here as well.

2021-04-16 15:29 UTC, colman-hartinger commented
> Is there a difference in meaning between a file named `types.ts` and `types.d.ts`?

Ya there is a difference the `.d` stands for a declaration file which I think is sort of analogous to `.h` files in c although I'm still learning how to use them. I know one of the benefits is that they will provide type annotations and definitions if the module is used in a pure JS application. 

That being said I think I'm going to change all the `.d.ts` to regular ts files until I learn a bit more since the ts compiler can generate `.d.ts` files for every file so I'm unsure of the usefulness of building our own

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

2021-04-16 15:55 UTC, bradymadams commented on src/api.ts
> +  _request(method, route, success, error, data?, header?: XHTTPHeader<string, string>) {
I wrote this out in my last review, but I must have forgotten to submit it. Anyway, I think we should either revert this to a single `encoding?: Encoding` argument like you had, or specify it as an array of headers. I think the former (single encoding argument) is better since this function is sort of responsible for setting up the whole request, so having arbitrary header arguments to this function sort of conflicts with it's intention.

2021-04-19 16:53 UTC, bradymadams commented on src/api.ts
> +        zlib.gzip(JSON.stringify(data), (_, gz) => {
I assume JSON.stringifying the 3MF data will result in an error somewhere. Did this work for you?

2021-04-19 17:19 UTC, bradymadams approved these changes

2021-04-19 17:19 UTC, merged