R21.0 formatting
tetonsim/thorjs pull request #30
Opened 2021-04-19 22:53 UTC by colman-hartinger

Some updated typescript formatting and definitions

2021-04-19 23:05 UTC, colman-hartinger commented on src/cli.ts
> +      muted?: boolean
@bradymadams I was a little unsure about doing this since it extends the base definition of a writable defined [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/stream.d.ts#L145) 

I was going over the nodejs/stream documentation but couldn't find any information on the muted property. If we think that it should be included in the typescript definition then we can open up a PR in the definitleyTyped library (linked above) adding that property, otherwise we should just keep this statement.

2021-04-19 23:05 UTC, colman-hartinger commented on src/types.ts
> +export interface Callback {
I thought it would be good to define a basic callback function since it's used all over the place in api.ts and cli.ts, I'm not sure if we should add more stringent definitions though

2021-04-20 14:24 UTC, bradymadams reviewed
Looks good. Couple of comments/questions:

1. The JS doc comments are probably redundant with these changes and will get out of sync if we're not careful to update them everytime we update a type in the TS source. Do you see any reason to keep them? If not, I think they should be removed.
2. If we're going to make api.ts strongly typed I do think we should fully define all the callbacks.

2021-04-20 15:38 UTC, colman-hartinger commented
1. Ya I also think the JS Doc comments are a bit redundant now and can be removed.
2. When defining the different callbacks do you think there should be anything different besides the name? From what I've seen and used, all the callbacks can be defined as a function that possibly takes some arguments and returns nothing

2021-04-20 15:57 UTC, bradymadams commented
> 2. When defining the different callbacks do you think there should be anything different besides the name? From what I've seen and used, all the callbacks can be defined as a function that possibly takes some arguments and returns nothing

If it's just the name that changes I don't think it's worth making different types. When I think of a strongly typed callback it should specify the arguments and the expected return type from the callback. As a developer calling a function that takes a callback I should be able to tell how to setup a proper callback. Is that possible?

2021-04-20 16:06 UTC, colman-hartinger commented
> If it's just the name that changes I don't think it's worth making different types. When I think of a strongly typed callback it should specify the arguments and the expected return type from the callback. As a developer calling a function that takes a callback I should be able to tell how to setup a proper callback. Is that possible?

Do any of the callbacks in thorjs have specific arguments or return types needed? When I was using them in exum It always seemed like I used a function with no arguments and a void return

2021-04-20 16:38 UTC, bradymadams commented
> Do any of the callbacks in thorjs have specific arguments or return types needed? When I was using them in exum It always seemed like I used a function with no arguments and a void return

Yes, they do. The jsdoc comments explain what they are. There are some generic callback signatures that are used commonly, but some functions have unique signatures with extra information (like the getToken and whoAmI callbacks).

2021-04-21 20:57 UTC, colman-hartinger commented
@bradymadams jsdoc type checking has been removed and explicit definitions for each callback type have been added.

2021-04-21 21:11 UTC, bradymadams requested changes
Is there a reason you chose to prefix some types with `API` and others without? The API prefix doesn't really seem necessary to me.

2021-04-21 21:11 UTC, bradymadams commented on src/types.ts
> +  export type Error = OneParamCallback<ObjectOrPrimitive>
I think it would be helpful to define the type so that the user can see how to get the error message sent in `param1`.

2021-04-21 21:11 UTC, bradymadams commented on src/types.ts
> +    (ObjectOrPrimitive): void
Can you explain these? It's not obvious to me how this defines a callback and how the user knows what type is sent as the argument.

2021-04-21 21:11 UTC, bradymadams commented on src/types.ts
> +    (arg0: ObjectOrPrimitive): void
What's the difference between this and `(ObjectOrPrimitive): void`?

2021-04-21 21:11 UTC, bradymadams commented on src/types.ts
> +}
I think we should define the properties of this type.

2021-04-21 21:11 UTC, bradymadams commented on src/types.ts
> +  export type APIMembers = {
TeamMembers

2021-04-21 21:11 UTC, bradymadams commented on src/types.ts
> +  interface APIInvite {
TeamInvite

2021-04-21 21:11 UTC, bradymadams commented on src/types.ts
> +  interface APIMembership {
TeamMembership

2021-04-21 21:45 UTC, colman-hartinger commented on src/types.ts
> +    (ObjectOrPrimitive): void
I was having a little trouble here as there isn't really any good way to clearly define the namespace that a callback operates in within TS. The next best thing in my mind was to structure how the callback is defined the same way you would define a class except for I used types because they aren't extendable.

If you navigate to the .d.ts tab [here](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDiCmAXAKgewNbwHbQN4ChpoJExEBXCAfgC5jEAnASywHND6wHFb7m2O2ACa8S-dkUZMwIAPokuPOmJYToUmbOGipAogAcGqIeWCJqdAIIMGYAJ4AeMFjsA+fB2CosY04lQMABQAlHgAvvhhQA) you can see how typescript would come up with the definitions for a simple class which is how I tried to structure the types.

As far as the argument goes, It didn't look like there were any restrictions on what that could be so I just set it to be a primitive type or generic object.

2021-04-21 21:57 UTC, bradymadams commented on src/types.ts
> +    (ObjectOrPrimitive): void
I'm definitely confused here, but why do we have to define the type structure and the callback all as one? In other languages I would separate them out, so something like this maybe:

```typescript
type User {
  email: string
  etc..
}

type GetTokenCallback = (User) => void;
```

> As far as the argument goes, It didn't look like there were any restrictions on what that could be so I just set it to be a primitive type or generic object.

The argument sent to the callback is well defined. Am I misunderstanding what `(ObjectOrPrimitive): void` is representing?

2021-04-21 22:16 UTC, colman-hartinger commented on src/types.ts
> +    (ObjectOrPrimitive): void
you're right about separating things out, I was pretty confused with how to properly define the callback so I went down the wrong route. 

I just remembered that when passing this into a function in ts it gets evaluated as null when converted to js so I can use that to set harder restrictions on the namespace that the callback is operating. example [here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATlAvFA3gKClCBbAQwEsAbALijmESIDsBzbKWgvCCqmhzAX001CQoAcQjAAKgHsA1hFoBhAiRIAjAgGNpqKAApgACyJwK8JAEpUAPigA3SUQAmAbn6YAZgFda64EUm0oN0lJHTgPdXUIOGMRMSlZBSVVDWkLLBwwiKi4XlcgkM9vX38dNKYDIwA6FjZywzhKpERJRF4zIA)

As far as passing ObjectOrPrimitive into the callback that is also my misunderstanding that the callback may be used with some argument but that is not the case except for `API.verifyVersion' so I'll change that so no other callback can accept an argument

2021-04-22 15:35 UTC, colman-hartinger commented
Alright I think everything is working pretty well now. In testing there's auto completion for `this` when writing a callback and the compiler will error if you try and access a property on `this` that isn't defined for the specific callback. This takes advantage of the typescript functionality of being able to pass `this` to a function and have the JS compilation be a function with no args

2021-04-22 18:49 UTC, bradymadams requested changes
This is certainly easier to understand. I'll try to play around with it some and write some code in an IDE to see how it works. The naming is a little inconsistent. Is there a reason some have a Response suffix, and others don't?

2021-04-22 18:49 UTC, bradymadams commented on src/types.ts
> +  export type Error = { (this: Message): void | { (ObjectOrPrimitive): void } } & {(ObjectOrPrimitive): void}
Can you explain this syntax. The `|` makes sense to me, but what does the `&` do?

Why are the `ObjectOrPrimitive` arguments needed?

2021-04-22 18:49 UTC, bradymadams commented on src/types.ts
> +interface GetTokenresponse {
Naming style is inconsistent. However, this isn't the response for the `/auth/token` endpoint. There is a `user` and a `token` attribute.

![image](https://user-images.githubusercontent.com/23110600/115769168-7a607480-a368-11eb-8376-9c00c42ce0ab.png)

2021-04-22 18:49 UTC, bradymadams commented on src/types.ts
> +export type APIJob = Buffer | BasicObject
How about `JobData` instead of `APIJob`? Also, couldn't we use the Job type you worked on in the previous PR instead of `BasicObject`?

2021-04-22 19:27 UTC, colman-hartinger commented on src/types.ts
> +  export type Error = { (this: Message): void | { (ObjectOrPrimitive): void } } & {(ObjectOrPrimitive): void}
when defining types you can use an Union ( `|` operator) or an Intersection (`&` operator). There were a couple places in api.ts where success or error is called with some string argument which is why I extended the definition so that the code could compile. I agree that this is a little messy so I'll work on getting these two statements cleaned up and more readable,

As far as the `ObjectOrPrimitive' argument goes I was passing that in as to have a more general description to how those callbacks could be used. If it should just be a primitive then that can be changed or we could define different callbacks for the scenarios where args may be passed to success or error

2021-04-22 19:30 UTC, colman-hartinger commented on src/types.ts
> +export type APIJob = Buffer | BasicObject
I was thinking that there may be some cases where the job data doesn't completely conform to the definition set in job.ts but now I'm realizing that if this tool is used correctly then the json job should always be in that format, so this will be changed

2021-04-22 19:41 UTC, colman-hartinger commented on src/types.ts
> +interface GetTokenresponse {
how the token response was defined in api.ts omitted the token object https://github.com/tetonsim/thorjs/blob/master/src/api.js#L263 and when checking `this` on the `GetToken` call these are the available objects

```{ email: 'colman.hartinger@tetonsim.com',
  email_verified: true,
  first_name: 'Colman',
  id: 'b97bb38df2b8482d99b021c7bc4047e7',
  last_name: 'Hartinger' }```

2021-04-22 20:09 UTC, colman-hartinger commented on src/types.ts
> +  export type Error = { (this: Message): void | { (ObjectOrPrimitive): void } } & {(ObjectOrPrimitive): void}
Ok I was able to get rid of the &'s and |'s by using the `call` command on the two situations in api.ts where Success and Error were called (Lines 295 and 276) 

Essentially the problem was  TS  saying "HEY, I'm noticing you're trying to invoke a function that has a this signature of A but you're bound to undefined".  

so calling
```
def foo(error: Callback.Error) {
   error('null token')  // Error The 'this' context of type 'void' is not assignable to method's 'this' of type 'Message'.ts(2684)
   error.call('null token') // compiles
}
```

2021-04-22 20:24 UTC, bradymadams commented on src/types.ts
> +interface GetTokenresponse {
Okay, got it. I guess I initially structured it like that when thorjs handled the token internally. The calling code can access the token via a class property though, right?

2021-04-22 20:40 UTC, colman-hartinger commented on src/types.ts
> +interface GetTokenresponse {
Ya the token is accessible as a class property

2021-04-22 20:46 UTC, colman-hartinger commented
@bradymadams I switched all the "Response" interfaces to all operate under a single "Response" namespace so the naming for those should now be more clear. Also now that I've applied 'call' to the couple instances where the basic error and success response were actually getting called I was able to shorten those definitions down to something a lot more readable and intuitive

2021-04-23 17:15 UTC, bradymadams approved these changes
Looks good @colman-hartinger. I like the user experience of using TS in an IDE. Much easier than raw JS.

2021-04-23 17:15 UTC, merged