env configuration
tetonsim/thorjs pull request #31
Opened 2021-04-19 23:46 UTC by colman-hartinger

Essentially there are 2 configurations here 

1: running in node
node can read from a .env file so this is straightforward

(implemented and tested)

2. running in a browser
the webpack file will read in the version from .env file for browser use

(implemented and not tested)

2021-04-19 23:51 UTC, colman-hartinger commented
I think having a .env file is a cleaner solution than trying to read in the package.json or creating [environmentVariables.js](https://stackoverflow.com/questions/36962601/node-js-how-to-use-environment-variables-in-json-file) file but I'm open to going either of those routes as well

2021-04-20 15:58 UTC, bradymadams requested changes
This looks good to me, but can we include the revision number in the .env file?

2021-04-23 17:47 UTC, colman-hartinger commented
@bradymadams revision number is now included in .env file

2021-04-23 18:31 UTC, bradymadams reviewed
Can we not do?

```
THOR_VERSION = 21.0.1
```

The env variable should be a string, so I think that should be fine, but if they need to be separate let's drop the `_NUMBER` suffix off the revision variable name.

Oh ya we can definitely do that, I thought that when you were asking to add a revision number you wanted a separate variable

2021-04-23 18:31 UTC, bradymadams commented on src/api.ts
> +
Added whitespace here and line 83.

2021-04-23 19:01 UTC, bradymadams approved these changes

2021-04-23 19:01 UTC, merged