fix job poll
tetonsim/thorjs pull request #41
Opened 2021-05-18 18:31 UTC by colman-hartinger

I wanted to use the poll job function in a synchronous style to fully make use of async-await.

i.e.
```
 const resp = await thorApi.submitSmartSliceJobAndPoll(job, jobPoll);
```
so `resp` has the finished job results. Before you would have to program logic in the callback to get the finished results.

Also, I changed how XMLHttpRequest is initialized. I was having some issues with the XMLHttpRequest when it was in an if statement (GCP would init the XMLHttpRequest object even when the if statement didn't hit ) so I changed the logic to a try-catch statement in `_request`

2021-05-18 20:40 UTC, bradymadams requested changes

2021-05-18 20:40 UTC, bradymadams commented on src/api.ts
> +    return await this.pollSmartSliceJob(response, poll);
Do we not need to check for any errors on the job submission here?

2021-05-18 20:40 UTC, bradymadams commented on src/api.ts
> +  }
Is this indentation correct?

2021-05-18 20:40 UTC, bradymadams commented on src/api.ts
> +      },
Did you change a style rule that added all these trailing commas?

2021-05-18 20:40 UTC, bradymadams commented on src/api.ts
> -          }
Don't we need to retain the functionality for the callback to request cancellation?

2021-05-18 20:40 UTC, bradymadams commented on src/api.ts
> +          });
I'm having a hard time understanding this. Can you explain to me how this works?

2021-05-18 20:43 UTC, colman-hartinger commented on src/api.ts
> +  }
nope

2021-05-18 20:43 UTC, colman-hartinger commented on src/api.ts
> +      },
I think I just forgot to run lint on my last PR

2021-05-18 20:45 UTC, colman-hartinger commented on src/api.ts
> +    return await this.pollSmartSliceJob(response, poll);
If there is an error it should be absorbed by the check in the codebase it's used in

2021-05-18 20:48 UTC, colman-hartinger commented on src/api.ts
> +          });
this is essentially just `time.sleep` in python. I was having some problems getting the right return value using `setTimeout` recursively so I decided to just go with a while loop to simplify the problem.

2021-05-18 21:20 UTC, colman-hartinger commented on src/api.ts
> +    return await this.pollSmartSliceJob(response, poll);
To clarify a bit more we want `submitSmartSliceJobAndPoll` to resolve to a job object or reject an error. If there was an error handling in this function it could also resolve to that error

2021-05-18 21:21 UTC, colman-hartinger commented on src/api.ts
> -          }
Yes that should of made it back in

2021-05-20 12:52 UTC, bradymadams requested changes
Looks really good, jus two minor requests.

2021-05-20 12:52 UTC, bradymadams commented on src/api.ts
> +            console.log('canceling job');
Capitalize "Canceling"

2021-05-20 12:52 UTC, bradymadams commented on src/api.ts
> +      },
Do you want to keep the trailing commas? I don't have a strong preference either way - whatever you think that standard style should be here.

2021-05-20 17:30 UTC, colman-hartinger commented
@bradymadams Let's keep the trailing commas, I don't have that strong of a preference either but since we're using the google style guide I don't see any reason to remove them

2021-05-20 17:32 UTC, bradymadams approved these changes

2021-05-20 17:33 UTC, merged