Fea Redesign
tetonsim/thorjs pull request #54
Opened 2021-12-08 03:03 UTC by AijunHall

Removed fea classes in favor of interfaces, and added subpackage.

Also changed Infill Pattern type to an enum, from my slack mention. I went off the [r22 pywim Infill Pattern enum](https://github.com/tetonsim/pywim/blob/f1fac144574cf64f510ae0bc1dcafc05c6ab8d82/pywim/am.py#L9-L16).

Contributes to #51

2021-12-08 14:58 UTC, bradymadams requested changes
Let's remove fea/result/database.ts. I don't think we'll be needing it in this library. Other than that, this looks good to me.

2021-12-08 14:58 UTC, bradymadams commented on src/am/types.ts
> +}
Semi-colon

2021-12-10 17:41 UTC, AijunHall commented
@bradymadams This should be good to go now.

@dheaney Sorry for the hold up, I was dealing with a weird runtime error that seemed to have popped out of nowhere. Typescript was fine before compiling (with tsc as well), but upon GrabCAD opening, the plugin wouldn't load due to thorjs having a "missing submodule"

Figured out the issue. The fix was to define the submodule interface files in the top level package.json.

Thats my off the cuff explanation, it might be a bit muddy. If that doesn't make sense, I can try to explain it more in-depth. I'm starting to understand how these exports/modules/submodules are typically structured better.

2021-12-11 21:59 UTC, bradymadams approved these changes

2021-12-11 21:59 UTC, merged