Oauth
tetonsim/thorjs pull request #59
Opened 2022-02-03 21:32 UTC by dheaney

This PR addresses #47.

This is basically a TypeScript implementation of [the thor integration in pywim](https://github.com/tetonsim/pywim/blob/73693f3fa31ad521fa163ead6eb89c6fdfd03ccf/pywim/http/thor.py). By setting up a local HTTP server in node, we can securely receive OAuth tokens from a browser window.

The `cli.ts` file now includes code for handling OAuth login. I've tested logging in, logging out, and submitting jobs.

2022-02-03 22:34 UTC, AijunHall reviewed
Good stuff :+1:

Just some formatting comments. 

Besides my comments below, `src/thor/cli.ts` and `src/thor/oauth.ts` both have inconsistent spacing with some if/else/for statements as well.

e.g `if (~)` vs `if(~)`.

2022-02-03 22:34 UTC, AijunHall commented on src/thor/cli.ts
> +  let [state, error]= await handler.start(false);
`=` spacing

2022-02-03 22:34 UTC, AijunHall commented on src/thor/oauth.ts
> +  _callback: (status: number | null, result: UserAuth|ApiResult) => any;
`UserAuth | ApiResult` spacing

2022-02-03 22:34 UTC, AijunHall commented on src/thor/oauth.ts
> +  _state: string;
Are these OAuthHandler class variables in snake case to fit in with our python back-end code? 
I would assume so, just wanted to ask to make sure.

2022-02-03 22:34 UTC, AijunHall commented on src/thor/oauth.ts
> +  constructor(client_id: string, host: string, api_request: (method: HTTPMethod, route: string, data?, encoding?: Encoding) => Promise<Response.Any>) {
Might be better if this is broken down into a multi-line constructor

2022-02-03 22:34 UTC, AijunHall commented on src/thor/oauth.ts
> +  setCallback(callback: (status: number | null, result: UserAuth|ApiResult) => any) {
`UserAuth | ApiResult` spacing

2022-02-03 23:10 UTC, bradymadams requested changes
Looks pretty good. I'll play around with the functionality later.

1. `else` and `else if` should go on the same line as the preceding closing bracket:

```javascript
if (condition) {
} else if (other) {
} else {
}
```
2.  There's some variables and arguments that need to be changed to `camelCase`.

2022-02-03 23:10 UTC, bradymadams commented on src/thor/oauth.ts
> +      scope: 'account.read,job.read,job.write',
Take scope in as an argument.

2022-02-03 23:10 UTC, bradymadams commented on src/thor/oauth.ts
> +      queryParams['provides'] = provider;
`'providers'`

2022-02-04 14:42 UTC, dheaney commented on src/thor/oauth.ts
> +  _state: string;
I use the leading _ to denote variables that should be treated as private, but I forgot that I can also use `private` in TS... Otherwise I need to change to camel case.

2022-02-05 01:55 UTC, AijunHall approved these changes
Looks good

2022-02-07 13:58 UTC, bradymadams approved these changes
Looks really good @dheaney and works great. I had a few minor formatting requests. Due to my schedule this week I just made the changes so I can merge this for you.

2022-02-07 13:59 UTC, merged